mojaloop/testing-toolkit-test-cases

collections/hub/golden_path/feature_tests/block_transfer.json
collections/hub/golden_path/feature_tests/get_transfers.json
collections/hub/golden_path/feature_tests/post_scenarios/positive.json
collections/hub/golden_path/feature_tests/post_scenarios/reserve_notification_positive_testfsp1_testfsp2.json

#1894: TTK tests for transfers positive scenarios and patch notifications

---

collections/hub/golden_path/bug fixes/Test for 4 decimal points #949.json
collections/hub/golden_path/bug fixes/Test for Bugfix #1378 - extension list missing.json
collections/hub/golden_path/bug fixes/Test for Bugfix #742 - Error code check.json
collections/hub/golden_path/bug fixes/Test for Bugfix #849 - missing ID for transfers and quotes.json
collections/hub/golden_path/bug fixes/Tests for Bugfix #1009 - ML Adapter and ALS service health should include broker status.json
collections/hub/golden_path/bug fixes/Tests for Bugfix #981 - Fix 500 http code instead of 400.json
collections/hub/golden_path/bug fixes/Tests for Bugfix #990 and #1016 - Quotes.json
collections/hub/golden_path/bug fixes/Tests for Bugfix #998 - Quoting service not using most recent endpoint.json
collections/hub/golden_path/bug fixes/other-bug-fixes.json
collections/hub/golden_path/p2p_on_us_transfers/p2p_money_transfer_on_us.json
collections/hub/golden_path/quoting_service/quoting_service.json
collections/hub/golden_path/transaction_request_service/Error-framework-authorizations.json
collections/hub/golden_path/transaction_request_service/authorizations.json
collections/hub/golden_path/transaction_request_service/error-framework.json
collections/hub/golden_path/transaction_request_service/received State.json
collections/hub/golden_path/transaction_request_service/rejected State.json
collections/hub/golden_path/transaction_request_service/transaction service health.json
collections/hub/golden_path/transaction_request_service/transaction_request_service_health.json

Adding tests for:
Transaction requests service
Quoting service
Bug fixes
On-US transfer

1897 v2 missing test cases

---

collections/hub/golden_path/feature_tests/transfer_negative_scenarios/payee_abort_v1.1.json

Fixes for payee_above_v1.1 test case failing periodically due to race-condition

feat(2151): helm-release-v12.1.0

---

collections/hub/golden_path/feature_tests/transfer_negative_scenarios/payee_invalid_fulfillment.json

- Fixes to GP negative scenarios for invalid fulfilment

fix(#2151): helm-release-v12.1.0

---

collections/hub/golden_path/settlement_management/Settlement-management-primary-currency-test.json

fixed typo in settlements collection

fixed a typo

---

collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_accent_unicode.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_burmese_unicode.json
environments/hub.json

changes:
- added a p2p test for accented characters that covers lookup and quoting (along with registration, setup needed)
- new set of env variables for this accented character test scenario

feat: unicode character names with accented characters and env variables (hub)

---

collections/hub/golden_path/feature_tests/p2p_money_transfer/master.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_subid_error_callback.json

- added test case for "p2p_money_transfer - p2p_unhappy_path with invalid subID at PayeeFSP" for https://github.com/mojaloop/project/issues/2505

feat(mojaloop/#2505): als-subid-error-callback-endpoint-not-implemented

---

collections/hub/other_tests/bulk_transfers/bulk-invalid-dfsp-name-header-and-body.json
collections/hub/other_tests/bulk_transfers/fspiop_protocol_validation.json
collections/hub/other_tests/bulk_transfers/negative_scenarios.json
collections/hub/other_tests/bulk_transfers/positive_scenarios.json

Update bulk test cases to error codes found in sequence diagram https://docs.mojaloop.io/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.1.1-bulk-prepare-handler-consume.html

refactor: update test cases for reworked bulk validation

---

collections/hub/other_tests/bulk_transfers/bulk-invalid-timestamp.json
collections/hub/other_tests/bulk_transfers/bulk-transfer-timeout-scenario.json

fix(mojaloop/#2863): update put /bulkTransfers status code test - [https://github.com/mojaloop/project/issues/2863](https://github.com/mojaloop/project/issues/2863)
- Fix Put request response to correct status code

fix(mojaloop/#2863): update put /bulkTransfers status code test

---

collections/hub/golden_path/settlement_cgs/newsetcgs.json

- added environment configs for accountId for testfsp1-4
- added environment config mapping for funds-in for account id

fix: cgs account-ids are hard-coded

---

collections/hub/other_tests/bulk_transfers/bulk-duplicated-transfers.json
collections/hub/other_tests/bulk_transfers/fspiop_protocol_validation.json
collections/hub/other_tests/bulk_transfers/negative_scenarios.json
collections/hub/other_tests/bulk_transfers/positive_scenarios.json
rules/sdk-bulk/response_rules.json

feat(mojaloop/#2975): mojaloop helm release v14.1.0 - https://github.com/mojaloop/project/issues/2975
- updates to support [Helm v14.1.0 WIP release](https://github.com/mojaloop/helm/pull/509)
fix(mojaloop/#3024): [core bulk] POST /bulkTransfers from Switch to PayeeFSP to use Switch as fspiop-source - https://github.com/mojaloop/project/issues/3024
- updated other/bulk_transfers to correctly reflect "DESTINATION" headers to switch

feat(mojaloop/#2975): mojaloop helm release v14.1.0

---

collections/hub/golden_path/settlement_cgs/newsetcgs.json

test(mojaloop/#2926): add delay to settlements to mitigate processing window state error - https://github.com/mojaloop/project/issues/2926

test(mojaloop/#2926): add delay to settlements to mitigate processing window state error

---

collections/hub/other_tests/sdk_tests/subscenario.json

Negative Test Scenarios for subscenario

---

collections/hub/other_tests/sdk_tests/subscenario.json

Reverts mojaloop/testing-toolkit-test-cases#108

Revert "Feat/subscenario negative tests"

---

collections/hub/other_tests/sdk_tests/subscenario.json

Reverts mojaloop/testing-toolkit-test-cases#107

Revert "Negative Test Scenarios for subscenario"

---

collections/hub/sdk_scheme_adapter/request-to-pay/basic/happy-path.json

feat([mojaloop/3347](https://github.com/mojaloop/project/issues/3347)): added-request-to-pay-transfer-test

feat(mojaloop/3347): added-request-to-pay-transfer-test

---

.gitignore
collections/hub/golden_path/feature_tests/transfer_negative_scenarios/fulfil-reserved-v1.0.json

fix(mojaloop/#3390): testing-toolkit-test-cases v15.0.1 GP Collection fails - https://github.com/mojaloop/project/issues/3390
- fixed fulfil-reserved-v1.0 test-cases with incorrect mapping for transferId

fix(mojaloop/#3390): testing-toolkit-test-cases v15.0.1 GP Collection fails

---

collections/hub/thirdparty/collection.json

fix([mojaloop/3388](https://github.com/mojaloop/project/issues/3388)): parameterized hardcoded currency in thirdparty tests

fix(mojaloop/3388): parameterized hardcoded currency in thirdparty tests

---

collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_accent_unicode.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_burmese_unicode.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_subid.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_subid_error_callback.json
collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_with_balance_checks.json

chore(mojaloop/#3759): add ws awaits for post participant req in tests - https://github.com/mojaloop/project/issues/3759
Add ws awaits for requests that potentially were causing a race condition is requests in some test cases.

chore(mojaloop/#3759): add ws awaits for post participant req in tests

---

rules/hub/rules_callback/default_iso.json
rules/mojaloop/ml-testing-toolkit/spec_files/rules_callback/default_iso.json

Keeping them in a seperate files for now since there is some copied script logic that doesn't translate well until we resolve some questions with iso api.

chore: add rough iso20022 callback rules for gp

---

collections/hub/HA/golden_path/feature_tests/funds_in/funds_in_ttk.json
collections/hub/HA/golden_path/feature_tests/funds_out/Reserve&Abort/funds_out_abort.json
collections/hub/HA/golden_path/feature_tests/funds_out/Reserve&Commit/funds_out_commit.json
collections/hub/golden_path/feature_tests/funds_in/funds_in_ttk.json
collections/hub/golden_path/feature_tests/funds_out/Reserve&Abort/funds_out_abort.json
collections/hub/golden_path/feature_tests/funds_out/Reserve&Commit/funds_out_commit.json
package.json

Add retries to tests which frequently fail due to timing

fix: add retries to flaky hub reconciliation balance test, fix typos
